Numpy 

In [21]:
import numpy as np
import math

In [3]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [5]:
b = np.array ([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
b.shape

(2, 3)

In [7]:
a.dtype

dtype('int64')

In [8]:
c = np.array([1.1,2.2,3.4,4.4])
c

array([1.1, 2.2, 3.4, 4.4])

In [9]:
c.dtype

dtype('float64')

In [16]:
# assing a lot of values to zeros and one using the data function
d = np.zeros((2,3))
print(d)

e = np.ones((2,3))
print(e)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [17]:
# To create a random array
np.random.rand(2,3)

array([[0.16774515, 0.81526277, 0.33073807],
       [0.01151254, 0.57107618, 0.51791012]])

In [24]:
# the first and secomnd element are and the third element is the skipping element
f = np.arange(10, 7000, 7)
f

array([  10,   17,   24,   31,   38,   45,   52,   59,   66,   73,   80,
         87,   94,  101,  108,  115,  122,  129,  136,  143,  150,  157,
        164,  171,  178,  185,  192,  199,  206,  213,  220,  227,  234,
        241,  248,  255,  262,  269,  276,  283,  290,  297,  304,  311,
        318,  325,  332,  339,  346,  353,  360,  367,  374,  381,  388,
        395,  402,  409,  416,  423,  430,  437,  444,  451,  458,  465,
        472,  479,  486,  493,  500,  507,  514,  521,  528,  535,  542,
        549,  556,  563,  570,  577,  584,  591,  598,  605,  612,  619,
        626,  633,  640,  647,  654,  661,  668,  675,  682,  689,  696,
        703,  710,  717,  724,  731,  738,  745,  752,  759,  766,  773,
        780,  787,  794,  801,  808,  815,  822,  829,  836,  843,  850,
        857,  864,  871,  878,  885,  892,  899,  906,  913,  920,  927,
        934,  941,  948,  955,  962,  969,  976,  983,  990,  997, 1004,
       1011, 1018, 1025, 1032, 1039, 1046, 1053, 10

In [ ]:
# the first and secomnd element are and the third element is the skipping element
f = np.arange(10, 7000, 7)
f

array([  10,   17,   24,   31,   38,   45,   52,   59,   66,   73,   80,
         87,   94,  101,  108,  115,  122,  129,  136,  143,  150,  157,
        164,  171,  178,  185,  192,  199,  206,  213,  220,  227,  234,
        241,  248,  255,  262,  269,  276,  283,  290,  297,  304,  311,
        318,  325,  332,  339,  346,  353,  360,  367,  374,  381,  388,
        395,  402,  409,  416,  423,  430,  437,  444,  451,  458,  465,
        472,  479,  486,  493,  500,  507,  514,  521,  528,  535,  542,
        549,  556,  563,  570,  577,  584,  591,  598,  605,  612,  619,
        626,  633,  640,  647,  654,  661,  668,  675,  682,  689,  696,
        703,  710,  717,  724,  731,  738,  745,  752,  759,  766,  773,
        780,  787,  794,  801,  808,  815,  822,  829,  836,  843,  850,
        857,  864,  871,  878,  885,  892,  899,  906,  913,  920,  927,
        934,  941,  948,  955,  962,  969,  976,  983,  990,  997, 1004,
       1011, 1018, 1025, 1032, 1039, 1046, 1053, 10

In [ ]:
#if we want too generate sequence of floats the third element isnt the total number of items we want to generate
np.linspace(0, 2, 13)

In [ ]:
# farehen height coversion
farenheit = np.array([0,-10,-5,-15,0])
celcius